type PartLike = {
  id: string;
  label: string;
  badge: string;
  blurb: string;
};

type PartOverride = Partial<Pick<PartLike, "label" | "badge" | "blurb">>;

const PART_OVERRIDES: Record<string, PartOverride> = {
  "expression-smile": { label: "Soft Smile", badge: "Core", blurb: "Gentle stitched smile for the current monster toy." },
  "expression-sleepy": { label: "Half Sleep", badge: "Dream", blurb: "Drooped eyes and a slower, drowsy read." },
  "expression-wink": { label: "Crooked Wink", badge: "Play", blurb: "Uneven wink for a more mischievous pose." },
  "expression-led": { label: "Scanner Visor", badge: "Bot", blurb: "Thin light visor with a machine-read mood." },
  "silhouette-bob": { label: "Mask Fringe", badge: "Shape", blurb: "Short wrapped fringe around the face shell." },
  "silhouette-curl": { label: "Bloom Curl", badge: "Shape", blurb: "Chunky spiral volume around the head." },
  "silhouette-bunny": { label: "Tall Ear Crest", badge: "Shape", blurb: "Long rising ear volume for strange pet heads." },
  "silhouette-bear": { label: "Round Cap", badge: "Shape", blurb: "Compact plush cap with a softer top line." },
  "silhouette-foam": { label: "Drift Crest", badge: "Shape", blurb: "Loose floating shell around fantasy heads." },
  "silhouette-shell": { label: "Plated Hood", badge: "Shape", blurb: "Hard surface hood for machine creatures." },
  "headpiece-cloud": { label: "Mist Puff", badge: "Topper", blurb: "Soft hovering puff above the head." },
  "headpiece-bow": { label: "Bone Bow", badge: "Topper", blurb: "Sharp ribbon shape with a stranger toy feel." },
  "headpiece-halo": { label: "Night Halo", badge: "Topper", blurb: "Rear halo that frames the silhouette without crowding it." },
  "headpiece-antenna": { label: "Signal Antenna", badge: "Topper", blurb: "Mechanical topper for scanning or hovering variants." },
  "outfit-pajama": { label: "Patch Coat", badge: "Body", blurb: "Soft stitched shell with a calmer toy silhouette." },
  "outfit-fairdress": { label: "Lantern Skirt", badge: "Body", blurb: "Swinging lower shell with a stage-like flare." },
  "outfit-plush": { label: "Plush Hide", badge: "Body", blurb: "Stuffed monster body with heavy softness." },
  "outfit-cape": { label: "Night Mantle", badge: "Body", blurb: "Draped fantasy shell with deeper rear volume." },
  "outfit-pod": { label: "Hard Shell", badge: "Body", blurb: "Rigid mech body with front plate emphasis." },
  "prop-ticket": { label: "Tag Charm", badge: "Prop", blurb: "Tiny charm card that feels more collectible than functional." },
  "prop-wand": { label: "Bone Rod", badge: "Prop", blurb: "Thin rod prop that reads like a ritual toy accessory." },
  "prop-lantern": { label: "Glow Jar", badge: "Prop", blurb: "Small carried light that adds a low eerie glow." },
  "prop-battery": { label: "Core Cell", badge: "Prop", blurb: "Compact energy core for machine variants." },
  "expression-luna-smile": { label: "Mask Smile", badge: "Maskling", blurb: "Porcelain face with a calm stitched smile." },
  "expression-luna-dream": { label: "Mask Drowse", badge: "Maskling", blurb: "Heavy-lid face made for the masked child." },
  "headpiece-luna-cloud": { label: "Patch Puff", badge: "Maskling", blurb: "Soft stuffed topper for the masked child." },
  "headpiece-luna-halo": { label: "Crack Halo", badge: "Maskling", blurb: "Split halo that echoes the broken porcelain face." },
  "outfit-luna-pajama": { label: "Bell Coat", badge: "Maskling", blurb: "Long stitched coat with a bell-heavy hem." },
  "outfit-luna-fairdress": { label: "Porcelain Tunic", badge: "Maskling", blurb: "Sharper body shell with a doll-like fall." },
  "expression-coco-wink": { label: "Spore Wink", badge: "Bloom Witch", blurb: "Wink face with garden-creature mischief." },
  "expression-coco-smile": { label: "Petal Smile", badge: "Bloom Witch", blurb: "Round smile softened by fungal cheeks." },
  "headpiece-coco-bow": { label: "Wilt Bow", badge: "Bloom Witch", blurb: "Bow shape that droops like soft petals." },
  "headpiece-coco-cloud": { label: "Mush Cap", badge: "Bloom Witch", blurb: "Tall cap topper inspired by clustered spores." },
  "outfit-coco-fairdress": { label: "Root Dress", badge: "Bloom Witch", blurb: "Wide lower shell with root-like layering." },
  "outfit-coco-pajama": { label: "Petal Cloak", badge: "Bloom Witch", blurb: "Softer wrapped shell with petal overlap." },
  "expression-aria-dream": { label: "Wax Drift", badge: "Candle Kid", blurb: "Sleepy face with softened melt lines." },
  "expression-aria-smile": { label: "Ash Smile", badge: "Candle Kid", blurb: "Small bright smile under a wick-lit brow." },
  "headpiece-aria-halo": { label: "Wick Crown", badge: "Candle Kid", blurb: "Tall crown that reads like a burning wick guard." },
  "headpiece-aria-bow": { label: "Ash Ribbon", badge: "Candle Kid", blurb: "Loose ribbon topper with soot-like tips." },
  "outfit-aria-fairdress": { label: "Wax Apron", badge: "Candle Kid", blurb: "Apron shell with melt drips and heavy front folds." },
  "outfit-aria-pajama": { label: "Cinder Robe", badge: "Candle Kid", blurb: "Long robe body with ash-dark edges." },
  "expression-bunny-smile": { label: "Triple Smile", badge: "Tri-Eye Rabbit", blurb: "Three-eye smile balanced around the center brow." },
  "expression-bunny-wink": { label: "Side Blink", badge: "Tri-Eye Rabbit", blurb: "One eye closes while the upper eye keeps staring." },
  "headpiece-bunny-bow": { label: "Burrow Bow", badge: "Tri-Eye Rabbit", blurb: "Small tied topper tucked between long ears." },
  "headpiece-bunny-cloud": { label: "Dust Puff", badge: "Tri-Eye Rabbit", blurb: "Soft puff topper with burrow dust volume." },
  "outfit-bunny-plush": { label: "Burrow Suit", badge: "Tri-Eye Rabbit", blurb: "Compact plush shell with wide paws." },
  "outfit-bunny-plush-puff": { label: "Pelt Puff", badge: "Tri-Eye Rabbit", blurb: "Rounder suit with denser stuffed volume." },
  "expression-bear-dream": { label: "Spore Dream", badge: "Mushroom Bear", blurb: "Sleepy face that droops under the mushroom cap." },
  "expression-bear-smile": { label: "Button Smile", badge: "Mushroom Bear", blurb: "Tiny smile with heavier cheek padding." },
  "headpiece-bear-cloud": { label: "Moss Puff", badge: "Mushroom Bear", blurb: "Soft crown of moss and spores." },
  "headpiece-bear-bow": { label: "Cap Bow", badge: "Mushroom Bear", blurb: "Wide bow tucked under a mushroom brim." },
  "outfit-bear-plush": { label: "Mush Vest", badge: "Mushroom Bear", blurb: "Rounded vest body with cap-like shoulders." },
  "outfit-bear-plush-cozy": { label: "Log Shell", badge: "Mushroom Bear", blurb: "Heavier body shell with bark-like seams." },
  "expression-fox-wink": { label: "Rover Wink", badge: "Doubletail Hound", blurb: "Play wink for the twin-tail hound." },
  "expression-fox-dream": { label: "Pant Dream", badge: "Doubletail Hound", blurb: "Relaxed sleepy face with a hanging tongue feel." },
  "headpiece-fox-bow": { label: "Collar Bow", badge: "Doubletail Hound", blurb: "Neck-tied bow shifted upward between the ears." },
  "headpiece-fox-cloud": { label: "Tail Puff", badge: "Doubletail Hound", blurb: "Topper that echoes the double tail tips." },
  "outfit-fox-plush": { label: "Rover Fur", badge: "Doubletail Hound", blurb: "Lean plush suit with long front paws." },
  "outfit-fox-plush-cape": { label: "Twin Tail Coat", badge: "Doubletail Hound", blurb: "Rear coat body that frames both tails." },
  "expression-axo-dream": { label: "Bubble Dream", badge: "Long-Ear Fish", blurb: "Slow pond stare with a drifting mouth line." },
  "expression-axo-smile": { label: "Gulp Smile", badge: "Long-Ear Fish", blurb: "Rounded smile shaped like a tiny gulp." },
  "headpiece-axo-halo": { label: "Fin Halo", badge: "Long-Ear Fish", blurb: "Rear ring that frames the floating fins." },
  "headpiece-axo-cloud": { label: "Drip Puff", badge: "Long-Ear Fish", blurb: "Wet, soft topper that hangs like water weight." },
  "outfit-axo-cape": { label: "Lagoon Cape", badge: "Long-Ear Fish", blurb: "Wide cape shell with water-drift edges." },
  "outfit-axo-cape-foam": { label: "Scale Foam", badge: "Long-Ear Fish", blurb: "Layered lower body with bubble clumps." },
  "expression-cloudling-smile": { label: "Stitch Smile", badge: "Ragbug", blurb: "Uneven smile stitched across the plush face." },
  "expression-cloudling-dream": { label: "Nest Dream", badge: "Ragbug", blurb: "Drooped thread eyes and a tiny stitched mouth." },
  "headpiece-cloudling-cloud": { label: "Pin Puff", badge: "Ragbug", blurb: "Stuffed topper pinned in place above the brow." },
  "headpiece-cloudling-halo": { label: "Thread Halo", badge: "Ragbug", blurb: "Loose stitched halo made from thread loops." },
  "outfit-cloudling-cape": { label: "Rag Cape", badge: "Ragbug", blurb: "Shredded fabric shell with hanging corners." },
  "outfit-cloudling-cape-soft": { label: "Pocket Body", badge: "Ragbug", blurb: "Soft round body with stitched patch pockets." },
  "expression-starmoth-dream": { label: "Pearl Dream", badge: "Shell Dragon", blurb: "Sleepy face tucked under the shell brow." },
  "expression-starmoth-smile": { label: "Tide Smile", badge: "Shell Dragon", blurb: "Small smile set inside a heavy snout plate." },
  "headpiece-starmoth-halo": { label: "Spine Halo", badge: "Shell Dragon", blurb: "Rear halo with small shell spines." },
  "headpiece-starmoth-cloud": { label: "Coral Puff", badge: "Shell Dragon", blurb: "Top crest that blooms like soft coral." },
  "outfit-starmoth-cape": { label: "Shell Mantle", badge: "Shell Dragon", blurb: "Rigid shoulder shell with a hanging rear flap." },
  "outfit-starmoth-cape-shine": { label: "Tide Cloak", badge: "Shell Dragon", blurb: "Smoother lower shell with pearl trim." },
  "expression-botu-led": { label: "Forest Scan", badge: "Owl Deer", blurb: "Wide scanning visor for the owl-deer bot." },
  "expression-botu-dream": { label: "Drowse Scan", badge: "Owl Deer", blurb: "Lower-powered visor with sleepy eye bars." },
  "headpiece-botu-antenna": { label: "Branch Antenna", badge: "Owl Deer", blurb: "Forked antenna inspired by antlers and twigs." },
  "headpiece-botu-antenna-plus": { label: "Lantern Rack", badge: "Owl Deer", blurb: "Expanded top rack with lantern-node tips." },
  "outfit-botu-pod": { label: "Forest Hull", badge: "Owl Deer", blurb: "Round body hull with deer-leg stance." },
  "outfit-botu-pod-mk2": { label: "Signal Torso", badge: "Owl Deer", blurb: "More layered chest shell with brighter front panel." },
  "expression-capsule-led": { label: "Hunt Visor", badge: "Night Fox", blurb: "Narrow hunter visor for the scout fox." },
  "expression-capsule-dream": { label: "Dim Visor", badge: "Night Fox", blurb: "Low-power visor with a softer read." },
  "headpiece-capsule-antenna": { label: "Radar Ears", badge: "Night Fox", blurb: "Tall pointed sensors shaped like fox ears." },
  "headpiece-capsule-antenna-plus": { label: "Needle Crown", badge: "Night Fox", blurb: "Sharper top crown built from scout pins." },
  "outfit-capsule-pod": { label: "Scout Pod", badge: "Night Fox", blurb: "Lean chassis with longer stride and rear mass." },
  "outfit-capsule-pod-mk2": { label: "Shadow Shell", badge: "Night Fox", blurb: "Stealth shell with narrower glass and tighter lines." },
  "expression-dronecat-led": { label: "Pulse Visor", badge: "Cloud Hedgehog", blurb: "Short pulse display for the hovering hedgehog bot." },
  "expression-dronecat-dream": { label: "Mist Visor", badge: "Cloud Hedgehog", blurb: "Blurred, dreamy visor with low-power glow." },
  "headpiece-dronecat-antenna": { label: "Quill Ring", badge: "Cloud Hedgehog", blurb: "Ring of short quill-like emitters." },
  "headpiece-dronecat-antenna-plus": { label: "Spark Array", badge: "Cloud Hedgehog", blurb: "Expanded emitter crown for the hover core." },
  "outfit-dronecat-pod": { label: "Puff Armor", badge: "Cloud Hedgehog", blurb: "Rounded armor shell with hedgehog body weight." },
  "outfit-dronecat-pod-mk2": { label: "Drift Core", badge: "Cloud Hedgehog", blurb: "Hover-ready belly shell with lighter rear mass." },
};

export function applyPartOverride<T extends PartLike>(part: T): T {
  const override = PART_OVERRIDES[part.id];
  if (!override) return part;
  return { ...part, ...override };
}
