export type FigureTheme = {
  id: string;
  title: string;
  atmosphere: string;
  effectLabel: string;
  keywords: [string, string, string];
  accentFrom: string;
  accentTo: string;
  aura: string;
  mist: string;
  pedestal: "chapel" | "bubble" | "plush" | "mech" | "dune" | "orbit" | "dessert" | "cloud";
  effect: "shards" | "bubbles" | "tags" | "scan" | "sand" | "orbit" | "sprinkles" | "fog" | "spores" | "scraps" | "bells" | "halo";
};

export const FIGURE_THEMES: Record<string, FigureTheme> = {
  "veil-nun": {
    id: "veil-nun",
    title: "静谧圣堂",
    atmosphere: "高挑、冷静、像一尊被摆进玻璃柜的瓷质修道雕像。",
    effectLabel: "断环光晕 + 垂直光束",
    keywords: ["圣堂感", "细长雕塑", "裂纹瓷面"],
    accentFrom: "#f8d9cb",
    accentTo: "#f2bda8",
    aura: "#ffe2d1",
    mist: "#f2ddd2",
    pedestal: "chapel",
    effect: "shards",
  },
  "bubble-diver": {
    id: "bubble-diver",
    title: "海底玩具舱",
    atmosphere: "像被做成盲盒收藏的潜水艇玩具，圆润、透明、带点童话海底感。",
    effectLabel: "泡泡群 + 海蓝体积光",
    keywords: ["透明舱体", "玩具潜水员", "软海洋感"],
    accentFrom: "#d5fbf6",
    accentTo: "#8fdacf",
    aura: "#bcfff3",
    mist: "#dff9f5",
    pedestal: "bubble",
    effect: "bubbles",
  },
  "post-dog": {
    id: "post-dog",
    title: "邮路棉偶",
    atmosphere: "像手缝的邮差犬玩偶，柔软、旧旧的、很有陪伴型收藏品气质。",
    effectLabel: "票签漂带 + 缝线尾迹",
    keywords: ["四足布偶", "棉布感", "递送设定"],
    accentFrom: "#eee1c4",
    accentTo: "#cbb07a",
    aura: "#f6ebd7",
    mist: "#ebe0cf",
    pedestal: "plush",
    effect: "tags",
  },
  "tin-wolf": {
    id: "tin-wolf",
    title: "巡逻机坪",
    atmosphere: "一只冷光巡逻狼站在检修平台上，硬朗、锋利、像收藏级机械模型。",
    effectLabel: "扫描线 + 环形雷达",
    keywords: ["机械四足", "硬边甲片", "冷光巡逻"],
    accentFrom: "#c4ebe7",
    accentTo: "#71b8ae",
    aura: "#9ff1e7",
    mist: "#dff7f4",
    pedestal: "mech",
    effect: "scan",
  },
  "dune-tortle": {
    id: "dune-tortle",
    title: "沙海遗壳",
    atmosphere: "低伏、缓慢、像一件从沙丘里挖出来的远古甲壳收藏品。",
    effectLabel: "沙弧背风 + 颗粒光圈",
    keywords: ["低趴异兽", "壳体比例", "沙海遗物"],
    accentFrom: "#f3e0bf",
    accentTo: "#d2ab67",
    aura: "#f0d79f",
    mist: "#eee0c8",
    pedestal: "dune",
    effect: "sand",
  },
  "mirror-snake": {
    id: "mirror-snake",
    title: "镜池盘灵",
    atmosphere: "盘绕、反光、像把灵体和首饰设计混在一起的高级收藏件。",
    effectLabel: "镜片轨道 + 灵珠悬浮",
    keywords: ["盘绕造型", "镜壳反光", "饰品感"],
    accentFrom: "#e3dbff",
    accentTo: "#9d87eb",
    aura: "#dac9ff",
    mist: "#ece6ff",
    pedestal: "orbit",
    effect: "orbit",
  },
  "frost-penguin": {
    id: "frost-penguin",
    title: "甜点展示柜",
    atmosphere: "一只被做成甜品装置的企鹅，重点是糖壳、奶油和可爱的陈列感。",
    effectLabel: "糖针星点 + 甜霜亮片",
    keywords: ["甜品玩具", "蛋形比例", "糖霜外壳"],
    accentFrom: "#ffd8d0",
    accentTo: "#ffae8d",
    aura: "#ffe1ce",
    mist: "#fff0e8",
    pedestal: "dessert",
    effect: "sprinkles",
  },
  "cloud-jelly": {
    id: "cloud-jelly",
    title: "浮空水母舱",
    atmosphere: "它不是站在台上，而是像被罩在一团云气里的悬浮收藏体。",
    effectLabel: "云雾体 + 浮游伴星",
    keywords: ["透明伞形", "漂浮气团", "空灵发光"],
    accentFrom: "#defcff",
    accentTo: "#9fdfe7",
    aura: "#c3f8ff",
    mist: "#e8ffff",
    pedestal: "cloud",
    effect: "fog",
  },
  "spore-bear": {
    id: "spore-bear",
    title: "菌林采集站",
    atmosphere: "像森林盲盒系列里的毛茸茸采菌熊，重点是茸感、暖色和孢子细节。",
    effectLabel: "孢子漂点 + 叶片影",
    keywords: ["森林毛绒", "大菌棚", "采集设定"],
    accentFrom: "#edf1d3",
    accentTo: "#b7c878",
    aura: "#e6efbb",
    mist: "#f1f4de",
    pedestal: "plush",
    effect: "spores",
  },
  "scrap-crow": {
    id: "scrap-crow",
    title: "拾荒码头",
    atmosphere: "瘦、尖、破旧又灵活，像废土系列里的高端收藏鸟形。",
    effectLabel: "金属碎片 + 钥匙吊环",
    keywords: ["鸟形角色", "拾荒设定", "薄片结构"],
    accentFrom: "#d8d2df",
    accentTo: "#9d92ae",
    aura: "#d7d1e5",
    mist: "#ece9f1",
    pedestal: "mech",
    effect: "scraps",
  },
  "sugar-lamb": {
    id: "sugar-lamb",
    title: "铃雪绒团",
    atmosphere: "一只被当成节日收藏品的羊羔，视觉重点是绒球、卷角和铃铛。",
    effectLabel: "铃光 + 绒圈",
    keywords: ["绒球动物", "节日收藏", "卷角造型"],
    accentFrom: "#fff0d6",
    accentTo: "#d8bc76",
    aura: "#fff0c7",
    mist: "#fff7e7",
    pedestal: "plush",
    effect: "bells",
  },
  "porcelain-deer": {
    id: "porcelain-deer",
    title: "瓷庭长像",
    atmosphere: "像高定艺术玩具里的长腿鹿人，重点是细腿、角和雕塑站姿。",
    effectLabel: "瓷环 + 角形背光",
    keywords: ["长腿雕塑", "鹿角构图", "高定展陈"],
    accentFrom: "#f5dfd4",
    accentTo: "#cdb49b",
    aura: "#ffe8df",
    mist: "#f7ece6",
    pedestal: "chapel",
    effect: "halo",
  },
};

export function getFigureTheme(id: string): FigureTheme {
  return FIGURE_THEMES[id] ?? FIGURE_THEMES["veil-nun"];
}
